import { Parser, Quad } from "n3";
import { writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));

const QUDT_UNIT_VOCAB = "https://qudt.org/vocab/unit";
// qudtlib-js unit IRIs use http:// (matching the Turtle file exactly)
const QUDT_UNIT_PREFIX = "http://qudt.org/vocab/unit/";
const RDFS_LABEL = "http://www.w3.org/2000/01/rdf-schema#label";
// All lowercase — compared case-insensitively
const SKIP_LANGS = new Set(["en", "en-us"]);

async function main() {
  console.log(`Fetching ${QUDT_UNIT_VOCAB} ...`);
  const response = await fetch(QUDT_UNIT_VOCAB, {
    headers: { Accept: "text/turtle" },
  });
  if (!response.ok) {
    throw new Error(`HTTP ${response.status}: ${response.statusText}`);
  }
  const turtle = await response.text();
  console.log(`Downloaded ${(turtle.length / 1024).toFixed(0)} KB`);

  const quads: Quad[] = await new Promise((resolve, reject) => {
    const parser = new Parser({ format: "text/turtle" });
    const collected: Quad[] = [];
    parser.parse(turtle, (error, quad, _prefixes) => {
      if (error) return reject(error);
      if (quad) {
        collected.push(quad);
      } else {
        resolve(collected);
      }
    });
  });

  console.log(`Parsed ${quads.length} quads`);

  // Build map: iri → [[text, languageTag], ...]
  const labelMap: Record<string, Array<[string, string]>> = {};

  for (const quad of quads) {
    if (
      quad.predicate.value !== RDFS_LABEL ||
      !quad.subject.value.startsWith(QUDT_UNIT_PREFIX) ||
      quad.object.termType !== "Literal"
    ) {
      continue;
    }

    const lang = quad.object.language;
    if (!lang || SKIP_LANGS.has(lang.toLowerCase())) continue;

    const iri = quad.subject.value;
    const text = quad.object.value;

    if (!labelMap[iri]) labelMap[iri] = [];
    labelMap[iri].push([text, lang]);
  }

  // Sort IRIs for deterministic diffs
  const sortedIris = Object.keys(labelMap).sort();
  let totalLabels = 0;

  const entries = sortedIris.map((iri) => {
    const pairs = labelMap[iri];
    // Sort pairs by language tag then text for determinism
    pairs.sort((a, b) => a[1].localeCompare(b[1]) || a[0].localeCompare(b[0]));
    totalLabels += pairs.length;
    const pairsStr = pairs
      .map(([text, tag]) => `    [${JSON.stringify(text)}, ${JSON.stringify(tag)}]`)
      .join(",\n");
    return `  ${JSON.stringify(iri)}: [\n${pairsStr}\n  ]`;
  });

  const isoDate = new Date().toISOString().slice(0, 10);
  const output = `// Generated by scripts/generate-labels.ts on ${isoDate}
// Source: ${QUDT_UNIT_VOCAB}
// Do not edit manually — run \`npm run generate\` to refresh
export const UNIT_LABELS: Record<string, Array<[string, string]>> = {
${entries.join(",\n")}
};
`;

  const outPath = join(__dirname, "../src/labels.ts");
  writeFileSync(outPath, output, "utf8");
  console.log(
    `Wrote ${sortedIris.length} IRIs, ${totalLabels} labels to src/labels.ts`
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
